spring:
  application:
    name: system-service
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848

  config:
    import:
      - nacos:mybatis.yml?refreshEnabled=true
      - nacos:datasource.yml?refreshEnabled=true
      - nacos:system-service.yml?refreshEnabled=true
      - nacos:dubbo.yml?refreshEnabled=true
