spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
    gateway:
      discovery:
        locator:
          lowerCaseServiceId: true
          enabled: true
      routes:
        # 认证中心
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth-service/**
          filters:
            - StripPrefix=1
        - id: system-service
          uri: lb://system-service
          predicates:
            - Path=/system-service/**
          filters:
            - StripPrefix=1

  config:
    import:
      - nacos:gateway.yml?refreshEnabled=true
      - nacos:dubbo.yml?refreshEnabled=true
      - nacos:redis.yml?refreshEnabled=true
      - nacos:sa-token.yml?refreshEnabled=true
